version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "80:80"
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-production-secret-key
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/processed:/app/backend/processed
      - ./logs:/app/backend/logs

volumes:
  redis_data: